### PR TITLE
Need a mechanism to determine build's state (based on the build ID) (…

### PR DESCRIPTION
**Pull request by karolh2000**
…enhancement #1254)

## Description

This issues implements a new feature described in [#1254](https://github.com/pyrsia/pyrsia/issues/1254), The idea is that users can check the status of the requested build.
New feature added to track the requested build state, from the user perspective the following CLI commands were added:
`pyrsia build status --id <BUILD ID>`

Few examples of returned messages:
`Build status for 'b024a136-9021-42a1-b8de-c665c94470f4' is 'RUNNING'`
`Build status for 'b024a136-9021-42a1-b8de-c665c94470f4' is 'SUCCESS'`
`Build status for 'f1548c9a-f2ee-46b9-8993-eed0a8e5c239' is 'FAILED'`

When the build ID is not found or expired:
`Build status for 'b024a136-9021-42a1-b8de-c665c94470f4' was not found. Additional info related to the build might be available via 'pyrsia inspect-log' command.`

The code follows patterns and style of other similar features including the "build request/start". It reuses the already existing API but also adds functionality to the CLI, build service, network and node API. New unit tests added also there is a pending integration test PR: [pyrsia/pyrsia-integration-tests#18](https://github.com/pyrsia/pyrsia-integration-tests/pull/18)

Fixes pyrsia/pyrsia#
The new feature is described here: [#1254](https://github.com/pyrsia/pyrsia/issues/1254)

This PR is a first step towards a more useful "build status" feature. Eventually, we should be able to add functionality which fetches the build logs and more. It should be relatively easy to add it based on this PR as long as the pipeline/build service supports it (provides API to get the build logs, etc).

## PR Checklist

- [x] I've read the [contributing guidelines](https://github.com/pyrsia/.github/blob/main/contributing.md).
- [x] I've read ["What is a Good PR?"](https://github.com/pyrsia/pyrsia/blob/main/docs/community/get_involved/good_pr.md)
- [x] I've included a good title and brief description along with how to review them.
- [x] I've linked any associated an [issue](https://github.com/pyrsia/pyrsia/issues).

### Code Contributions

- [x] I've built the code `cargo build --all-targets` successfully.
- [x] I've run the unit tests `cargo test --workspace` and everything passes.

### CODE REVIEW

**Comment by erwin1** [comment]
@karolh2000 did you notice the clippy error on GhA? https://github.com/pyrsia/pyrsia/actions/runs/3605219431/jobs/6075385186#step:6:1213

**Comment by karolh2000** [comment]
> 

@erwin1 I think clippy 1.65 is broken and it "panics" and fails when it builds the sources (logs below). It works fine with `clippy nightly` (1.67, `rustup default nightly`) so I'm assuming this is clippy related problem and we might have to turn off clippy until 1.67? BTW I created a new clippy issue for the problem (https://github.com/rust-lang/rust-clippy/issues/10034)

**CLIPPY 1.67 (FAILS)**

```
karolh@karolh-mac pyrsia % cargo clippy
    Checking pyrsia v0.2.1 (/Users/karolh/trunk/karolh2000/pyrsia)
error: internal compiler error: compiler/rustc_middle/src/ty/subst.rs:626:9: type parameter `Self/#0` (Self/0) out of range when substituting, substs=[]

thread 'rustc' panicked at 'Box<dyn Any>', /rustc/897e37553bba8b42751c67658967889d11ecd120/compiler/rustc_errors/src/lib.rs:1462:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.1.65 (897e3755 2022-11-02)

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `pyrsia`
```

**CLIPPY 1.67 nightly (SUCCESSFUL, the warnings are not related to the PR/changes)**

```
   Compiling pyrsia v0.2.1 (/Users/karolh/trunk/karolh2000/pyrsia)
error[E0277]: the type `UnsafeCell<backtrace::Capture>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
  --> src/artifact_service/storage.rs:51:50
   |
51 |       let panic_wrapper = std::panic::catch_unwind(|| match result {
   |  _________________________------------------------_^
   | |                         |
   | |                         required by a bound introduced by this call
52 | |         Ok(unwrapped) => unwrapped,
53 | |         Err(error) => {
54 | |             let msg = format!("Error initializing {}, error is: {}", label, error);
...  |
57 | |         }
58 | |     });
   | |_____^ `UnsafeCell<backtrace::Capture>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
   |
   = help: within `anyhow::error::ErrorImpl`, the trait `RefUnwindSafe` is not implemented for `UnsafeCell<backtrace::Capture>`
   = note: required because it appears within the type `backtrace::LazilyResolvedCapture`
   = note: required because it appears within the type `backtrace::Inner`
   = note: required because it appears within the type `Backtrace`
   = note: required because it appears within the type `std::option::Option<Backtrace>`
   = note: required because it appears within the type `anyhow::error::ErrorImpl`
   = note: required for `NonNull<anyhow::error::ErrorImpl>` to implement `UnwindSafe`
   = note: required because it appears within the type `anyhow::ptr::Own<anyhow::error::ErrorImpl>`
   = note: required because it appears within the type `anyhow::Error`
   = note: required because it appears within the type `Result<T, anyhow::Error>`
note: required because it's used within this closure
  --> src/artifact_service/storage.rs:51:50
   |
51 |     let panic_wrapper = std::panic::catch_unwind(|| match result {
   |                                                  ^^
note: required by a bound in `std::panic::catch_unwind`

error[E0277]: the type `UnsafeCell<backtrace::Capture>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
  --> src/util/keypair_util.rs:53:50
   |
53 |       let panic_wrapper = std::panic::catch_unwind(|| match result {
   |  _________________________------------------------_^
   | |                         |
   | |                         required by a bound introduced by this call
54 | |         Ok(unwrapped) => unwrapped,
55 | |         Err(error) => {
56 | |             let msg = format!("Error initializing {}, error is: {}", label, error);
...  |
59 | |         }
60 | |     });
   | |_____^ `UnsafeCell<backtrace::Capture>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
   |
   = help: within `anyhow::error::ErrorImpl`, the trait `RefUnwindSafe` is not implemented for `UnsafeCell<backtrace::Capture>`
   = note: required because it appears within the type `backtrace::LazilyResolvedCapture`
   = note: required because it appears within the type `backtrace::Inner`
   = note: required because it appears within the type `Backtrace`
   = note: required because it appears within the type `std::option::Option<Backtrace>`
   = note: required because it appears within the type `anyhow::error::ErrorImpl`
   = note: required for `NonNull<anyhow::error::ErrorImpl>` to implement `UnwindSafe`
   = note: required because it appears within the type `anyhow::ptr::Own<anyhow::error::ErrorImpl>`
   = note: required because it appears within the type `anyhow::Error`
   = note: required because it appears within the type `Result<T, anyhow::Error>`
note: required because it's used within this closure
  --> src/util/keypair_util.rs:53:50
   |
53 |     let panic_wrapper = std::panic::catch_unwind(|| match result {
   |                                                  ^^
note: required by a bound in `std::panic::catch_unwind`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `pyrsia` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by karolh2000** [comment]
PR to disable the clippy warnings: https://github.com/pyrsia/pyrsia/pull/1378

**Comment by karolh2000** [comment]
All issues and conflicts resolved, please take a look @tiainen @jperedadnr, thanks!

**Comment by tiainen** [comment]
I've tested the functionality and it all seems to work fine. I got the correct response both when asking the build status from an authorized node and a regular node.

I only have one remark: wouldn't it be nice to also propagate the error message back to the client in case of a failure? Currently, the actual error is ignored: https://github.com/pyrsia/pyrsia/pull/1360/files#diff-459f5dc9cbc7765c794b21667a5ccea2a16aa313e7f99a0ed035756d62a6086fR267

**Comment by karolh2000** [comment]
> I've tested the functionality and it all seems to work fine. I got the correct response both when asking the build status from an authorized node and a regular node.
> 
> I only have one remark: wouldn't it be nice to also propagate the error message back to the client in case of a failure? Currently, the actual error is ignored: https://github.com/pyrsia/pyrsia/pull/1360/files#diff-459f5dc9cbc7765c794b21667a5ccea2a16aa313e7f99a0ed035756d62a6086fR267

@tiainen Makes sense, will take a look and improve the failure error handling, thanks.

**Comment by karolh2000** [comment]
> > I've tested the functionality and it all seems to work fine. I got the correct response both when asking the build status from an authorized node and a regular node.
> > I only have one remark: wouldn't it be nice to also propagate the error message back to the client in case of a failure? Currently, the actual error is ignored: https://github.com/pyrsia/pyrsia/pull/1360/files#diff-459f5dc9cbc7765c794b21667a5ccea2a16aa313e7f99a0ed035756d62a6086fR267
> 
> @tiainen Makes sense, will take a look and improve the failure error handling, thanks.

The suggested changes implemented, the string contains the BuildStatus::Failure message.

**Review by tiainen — APPROVED** [review]

**Review by fishseabowl — APPROVED** [review]
Great. It's a nice real-time status check.

**Comment by erwin1** [comment]
tested and works nicely. one additional improvement (for a new issue) could be the option to chose for processing friendly output from the CLI, so one can more easily get the build ID. 

As a side note: I had a bug in the config edit that is now fixed on main. Maybe you should update and let the tests run again before merging.

**Review by erwin1 — APPROVED** [review]
